name: Latest blog post workflow
on:
    workflow_run:

jobs:
    update-readme-with-blog:
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                max_post_count: "5"
                feed_list: "https://medium.com/feed/@nicko170"
                template: "- [$title]($url): $description $newline"
                date_format: "UTC:ddd yyyy-mm-dd h:MM:ss TT Z"
                filter_comments: "medium"
                tag_post_pre_newline: "true"
                item_exec: |
                     post.description = post.description.replace(/<\/?[^>]+(>|$)/g, ""); 
